@host = https://localhost:5001

@access_token = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL2V4YW1wbGUuY29tIiwiaXNzIjoiaHR0cHM6Ly9zYWdlcy5wbCIsImV4cCI6MTc2NDkzMjg3MywianRpIjoiMzYyMDQ0MjUtMTA1MS00ODM1LTkwODUtZDg1ZWM5Zjc5ODg4IiwibmFtZSI6ImpvaG4iLCJlbWFpbCI6ImpvaG5AZG9tYWluLmNvbSIsInBob25lX251bWJlciI6bnVsbCwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IlNtaXRoIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiZGV2ZWxvcGVyIiwiaWF0IjoxNzY0OTMxOTczLCJuYmYiOjE3NjQ5MzE5NzN9.9YpHgVLrGaD6qvqy7QG3KXBD0Rf5bRCydJOKEp0HGLc

POST {{host}}/api/cart
Content-Type: application/json

{
    "Id": 1,
    "Quantity": 3
}

###

POST {{host}}/api/cart/checkout
Authorization: Bearer {{access_token}}

###
